disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
  - todo
  - function_body_length
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
  - file_length
  - type_body_length
  - nesting
  - inclusive_language
excluded:
  - Carthage
  - Deploy
  - build
type_name:
  max_length: 40
  excluded:
    - T # generic typealias usually
    - D # Debug logging helper
function_parameter_count:
  warning: 7