name: build

on:
  push:
    branches:
      - develop
      - main
      - release/*
  pull_request:

jobs:
  build:
    name: Build
    runs-on: macos-15
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Set proper xcode version
        run: sh ./scripts/xcodeselect.sh
      - name: Building
        run: ./scripts/build.sh
