name: build

on:
  push:
    branches:
      - develop
      - main
      - release/*
  pull_request:
  schedule:
    - cron: '25 6 * * *'

jobs:
  build:
    name: Build
    runs-on: macos-12
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set proper xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.0'
      - name: Building
        run: ./scripts/build.sh