name: lint

on:
  push:
    branches:
      - develop
      - release/*
  pull_request:

jobs:
  swift:
    name: Swift Lint
    runs-on: macos-26
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Lint
        run: ./scripts/swiftlint.sh