name: lint

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  pod:
    name: Pod Lib Lint
    runs-on: macos-13
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set proper xcode version
        run: sh ./scripts/xcodeselect.sh
      - name: Lint
        run: pod lib lint --allow-warnings
  swift:
    name: Swift Lint
    runs-on: macos-13
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Lint
        run: swiftlint --strict