name: lint

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  swift:
    name: Swift Lint
    runs-on: macos-13
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Lint
        run: swiftlint --strict